# Generated by Django 6.1.1 on 2026-09-25 20:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Huesped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('documento_identidad', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='habitacion',
            old_name='precio',
            new_name='precio_por_noche',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='creado_en',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='actualizado_en',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='habitacion',
            name='capacidad_personas',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habitacion',
            name='detalles',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='tipo',
            field=models.CharField(choices=[('IND', 'Individual'), ('DOB', 'Doble'), ('SUI', 'Suite Temática LaManchaland')], default='IND', max_length=3),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='categoria_estrellas',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='hotel',
            name='descripcion',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='email_contacto',
            field=models.EmailField(default='Sin descripción', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='telefono',
            field=models.CharField(default='000000000', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habitaciones', to='hoteles.hotel'),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='numero',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='direccion',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_check_in', models.DateField()),
                ('fecha_check_out', models.DateField()),
                ('estado', models.CharField(choices=[('PEN', 'Pendiente'), ('CON', 'Confirmada'), ('CAN', 'Cancelada'), ('FIN', 'Finalizada')], default='PEN', max_length=3)),
                ('total_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='hoteles.habitacion')),
                ('huesped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='hoteles.huesped')),
            ],
        ),
    ]
